apiVersion: v1
kind: Template
labels:
  template: service-portal-api
metadata:
  name: service-portal-api
  annotations:
    iconClass: icon-rails
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: "service-portal-api-secrets"
  stringData:
    pg-password: "${DATABASE_PASSWORD}"
- apiVersion: v1
  kind: Service
  metadata:
    name: "${DATABASE_SERVICE_NAME}"
    annotations:
      description: Exposes the database server
  spec:
    ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
    selector:
      name: "${DATABASE_SERVICE_NAME}"
- apiVersion: v1
  kind: Service
  metadata:
    name: service-portal-api
  spec:
    ports:
    - name: service-portal-api
      port: 8080
      targetPort: 3000
    selector:
      name: service-portal-api
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "service-portal-api-${DATABASE_SERVICE_NAME}"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${DATABASE_VOLUME_CAPACITY}"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${DATABASE_SERVICE_NAME}"
    annotations:
      description: Defines how to deploy the database
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      name: "${DATABASE_SERVICE_NAME}"
    template:
      metadata:
        name: "${DATABASE_SERVICE_NAME}"
        labels:
          name: "${DATABASE_SERVICE_NAME}"
      spec:
        volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: "service-portal-api-${DATABASE_SERVICE_NAME}"
        containers:
        - name: postgresql
          image: "${POSTGRESQL_IMG_NAME}:${POSTGRESQL_IMG_TAG}"
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: postgres-volume
            mountPath: "/var/lib/pgsql/data"
          env:
          - name: POSTGRESQL_USER
            value: "${DATABASE_USER}"
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "service-portal-api-secrets"
                key: pg-password
          - name: POSTGRESQL_DATABASE
            value: "${DATABASE_NAME}"
          - name: POSTGRESQL_MAX_CONNECTIONS
            value: "${POSTGRESQL_MAX_CONNECTIONS}"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: service-portal-api
  spec:
    replicas: 1
    selector:
      name: service-portal-api
    template:
      metadata:
        name: service-portal-api
        labels:
          name: service-portal-api
      spec:
        containers:
        - name: service-portal-api
          image: service-portal-ci/service-portal-api:latest
          ports:
          - containerPort: 3000
          env:
          - name: DATABASE_USER
            value: "${DATABASE_USER}"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: service-portal-api-secrets
                key: pg-password
          - name: DATABASE_NAME
            value: "${DATABASE_NAME}"
          - name: DATABASE_HOST
            value: "${DATABASE_SERVICE_NAME}"
          - name: DATABASE_PORT
            value: "5432"
          readinessProbe:
            timeoutSeconds: 1
            tcpSocket:
              port: 3000
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - service-portal-api
          from:
            kind: ImageStreamTag
            name: service-portal-api:latest
parameters:
- name: DATABASE_SERVICE_NAME
  displayName: PostgreSQL Service Name
  required: true
  description: The name of the OpenShift Service exposed for the PostgreSQL container.
  value: postgresql
- name: DATABASE_USER
  displayName: PostgreSQL User
  required: true
  description: PostgreSQL user that will access the database.
  value: root
- name: DATABASE_PASSWORD
  displayName: PostgreSQL Password
  required: true
  description: Password for the PostgreSQL user.
  from: "[a-zA-Z0-9]{8}"
  generate: expression
- name: DATABASE_NAME
  required: true
  displayName: PostgreSQL Database Name
  description: Name of the PostgreSQL database accessed.
  value: service_portal_production
- name: POSTGRESQL_MAX_CONNECTIONS
  displayName: PostgreSQL Max Connections
  description: PostgreSQL maximum number of database connections allowed.
  value: '100'
- name: POSTGRESQL_IMG_NAME
  displayName: PostgreSQL Image Name
  description: This is the PostgreSQL image name requested to deploy.
  value: docker.io/manageiq/postgresql
- name: POSTGRESQL_IMG_TAG
  displayName: PostgreSQL Image Tag
  description: This is the PostgreSQL image tag/version requested to deploy.
  value: latest
- name: DATABASE_VOLUME_CAPACITY
  displayName: Database Volume Capacity
  required: true
  description: Volume space available for database.
  value: 15Gi
