apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-portal-postgresql
  labels:
    app: service-portal
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
