apiVersion: v1
kind: Template
labels:
  template: catalog-database-secrets
metadata:
  name: catalog-database-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: catalog-database-secrets
    labels:
      app: catalog
  stringData:
    database-password: "${DATABASE_PASSWORD}"
    database-url: postgresql://root:${DATABASE_PASSWORD}@catalog-postgresql:5432/service_portal_production?encoding=utf8&pool=5&wait_timeout=5
parameters:
- name: DATABASE_PASSWORD
  displayName: PostgreSQL Password
  required: true
  description: Password for the PostgreSQL user.
  from: "[a-zA-Z0-9]{8}"
  generate: expression
