apiVersion: v1
kind: Template
labels:
  template: catalog-database-secrets
metadata:
  name: catalog-database-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: catalog-db
    labels:
      app: catalog
  stringData:
    hostname: catalog-postgresql
    password: "${DATABASE_PASSWORD}"
    username: root
parameters:
- name: DATABASE_PASSWORD
  displayName: PostgreSQL Password
  required: true
  description: Password for the PostgreSQL user.
  from: "[a-zA-Z0-9]{8}"
  generate: expression
