apiVersion: v1
kind: Service
metadata:
  name: service-portal-postgresql
  labels:
    app: service-portal
spec:
  ports:
  - name: service-portal-postgresql
    port: 5432
    targetPort: 5432
  selector:
    name: service-portal-postgresql
