apiVersion: v1
kind: Service
metadata:
  name: catalog-postgresql
  labels:
    app: catalog
spec:
  ports:
  - name: catalog-postgresql
    port: 5432
    targetPort: 5432
  selector:
    name: catalog-postgresql
