apiVersion: v1
kind: DeploymentConfig
metadata:
  name: catalog-kafka
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    name: catalog-kafka
  template:
    metadata:
      name: catalog-kafka
      labels:
        name: catalog-kafka
        app: catalog
    spec:
      containers:
      - name: catalog-kafka
        image: manageiq/kafka:latest
        command:
        - bin/kafka-server-start.sh
        args:
        - config/server.properties
        - --override
        - advertised.host.name=catalog-kafka
        - --override
        - log.segment.bytes=10485760
        - --override
        - log.retention.bytes=10485760
        volumeMounts:
        - mountPath: /tmp/kafka-logs
          name: catalog-kafka-logs
        ports:
        - containerPort: 9092
      - name: catalog-zookeeper
        image: manageiq/kafka:latest
        command:
        - bin/zookeeper-server-start.sh
        args:
        - config/zookeeper.properties
        volumeMounts:
        - mountPath: /tmp/zookeeper
          name: catalog-zookeeper
        ports:
        - containerPort: 2181
      volumes:
      - name: catalog-kafka-logs
        emptyDir: {}
      - name: catalog-zookeeper
        emptyDir: {}
