apiVersion: v1
kind: Service
metadata:
  name: service-portal-kafka
  labels:
    app: service-portal
spec:
  ports:
  - name: service-portal-kafka
    port: 9092
  - name: service-portal-zookeeper
    port: 2181
  selector:
    name: service-portal-kafka
