apiVersion: v1
kind: Service
metadata:
  name: catalog-kafka
  labels:
    app: catalog
spec:
  ports:
  - name: catalog-kafka
    port: 9092
  - name: catalog-zookeeper
    port: 2181
  selector:
    name: catalog-kafka
