apiVersion: v1
kind: DeploymentConfig
metadata:
  name: service-portal-api
  labels:
    app: service-portal
spec:
  replicas: 1
  selector:
    name: service-portal-api
  template:
    metadata:
      name: service-portal-api
      labels:
        app: service-portal
        name: service-portal-api
    spec:
      containers:
      - name: service-portal-api
        image: service-portal-ci/service-portal-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: service-portal-database-secrets
              key: database-password
        - name: DATABASE_NAME
          value: service_portal_production
        - name: DATABASE_HOST
          value: service-portal-postgresql
        - name: DATABASE_PORT
          value: "5432"
        readinessProbe:
          tcpSocket:
            port: 3000
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - service-portal-api
        from:
          kind: ImageStreamTag
          name: service-portal-api:latest
