apiVersion: v1
kind: Template
labels:
  template: catalog-api-secrets
metadata:
  name: catalog-api-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: catalog-api-secrets
    labels:
      app: catalog
  stringData:
    secret-key: "${SECRET_KEY}"
    encryption-key: "${ENCRYPTION_KEY}"
parameters:
- name: SECRET_KEY
  displayName: Secret Key
  required: true
  description: Rails SECRET_KEY_BASE
  from: "[a-f0-9]{128}"
  generate: expression
- name: ENCRYPTION_KEY
  displayName: Encryption Key
  required: true
  description: Encryption Key for Passwords
  from: "[a-zA-Z0-9]{43}"
  generate: expression
