apiVersion: v1
kind: Service
metadata:
  name: service-portal-api
  labels:
    app: service-portal
spec:
  ports:
  - name: service-portal-api
    port: 8080
    targetPort: 3000
  selector:
    name: service-portal-api
